### ISSUE TITLE
Make 1.0 release

### ISSUE THREAD

**Issue by aragilar** [h5preserve/h5preserve#6]
- [x] Reach near 100% coverage of main module
- [ ] Support remainder of h5py classes (#4)
- [ ] Add dumping/loading of attributes (#5)
- [x] Sort out DatasetContainer API (#7)
- [x] Document how versioning works (#8)
- [x] Cleanup quickstart and make doctestable (#9)
- [x] Cleanup API docs (#10)
- [x] Document additional registries (#11)
- [x] Add proper usage docs (#12)
